version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline 
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
