version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/nodejs-aws-codedeploy-pipeline
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
